name: Build Windows Export

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Install required tools for unzipping, Python, and JSON processing
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip jq python3
    
      # Set build variables from the JSON config using Python.
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Set Build Variables
      run: python3 .github/export_vars.py
    
    - name: Restore caches
      uses: actions/cache@v4
      with:
        path: .godot/
        key: game-jam-autobuild-caches-godot-${{ github.repository }}
    
    - name: Install Wine for Windows EXE logo
      id: wine_install
      run: |
        sudo apt install wine64
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT

    - name: Export Godot project
      id: export-normal
      uses: firebelley/godot-export@v6.0.0
      with:
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
        cache: true
        relative_project_path: "."
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
        archive_output: true

    - name: Export debug version
      id: export-debug
      uses: firebelley/godot-export@v6.0.0
      with:
        export_debug: true
        godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip
        godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz
        cache: true
        relative_project_path: "."
        wine_path: ${{ steps.wine_install.outputs.WINE_PATH }}
        archive_output: true
    
    - name: Upload normal build
      if: ${{ steps.export-normal.outcome == success() }}
      id: normal-build-upload
      uses: actions/upload-artifact@v4
      with:
        name: normal builds
        path: ${{ steps.export-normal.outputs.build_directory }}/*
    - name: Upload debug build
      id: debug-build-upload
      uses: actions/upload-artifact@v4
      with:
        name: debug builds
        path: ${{ steps.export-debug.outputs.build_directory }}/*

    - name: Upload archives
      id: normal-archive-upload
      uses: actions/upload-artifact@v4
      with:
        name: normal build archives
        path: ${{ steps.export-normal.outputs.archive_directory }}/*
    - name: Upload debug archive
      id: debug-archive-upload
      uses: actions/upload-artifact@v4
      with:
        name: debug build archives
        path: ${{ steps.export-debug.outputs.archive_directory }}/*
      
    - name: Warn if an upload or build fails
      id: warn-on-failures
      run: |
        if [ "${{ steps.export-normal.outcome }}" != "success" ]; then
          curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Run ID ${{ github.run_id }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}, commit ${{ github.sha }}) failed to build normally!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
        if [ "${{ steps.export-debug.outcome }}" != "success" ]; then
          curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Run ID ${{ github.run_id }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}, commit ${{ github.sha }}) failed to build a debug version!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}

        if [ "${{ steps.normal-build-upload.outcome }}" == "failure" ]; then
          curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Run ID ${{ github.run_id }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}, commit ${{ github.sha }}) failed to upload normal build!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
        if [ "${{ steps.debug-build-upload.outcome }}" == "failure" ]; then
          curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Run ID ${{ github.run_id }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}, commit ${{ github.sha }}) failed to upload debug build!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
        if [ "${{ steps.normal-archive-upload.outcome }}" == "failure" ]; then
          curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Run ID ${{ github.run_id }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}, commit ${{ github.sha }}) failed to upload normal archive!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
        if [ "${{ steps.debug-archive-upload.outcome }}" == "failure" ]; then
          curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Run ID ${{ github.run_id }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}, commit ${{ github.sha }}) failed to upload debug archive!\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
        fi

    # Post the artifact download URL to a Discord webhook.
    - name: Post artifact link to Discord
      run: |
        curl -H "Content-Type: application/json" \
             -d "{\"content\": \"Commit ${{ github.sha }} (branch ref: ${{ github.repository }}@${{ github.ref_name }}) now has a build artifact available! Download it here:\n\nBinaries\n[Normal](${{ steps.normal-build-upload.outputs.artifact-url }}) | [Debug](${{ steps.debug-build-upload.outputs.artifact-url }})\n\nArchives\n[Normal](${{ steps.normal-archive-upload.outputs.artifact-url }}) | [Debug](${{ steps.debug-archive-upload.outputs.artifact-url }})\n\n-# Artifacts expire after 90 days of being uploaded.\n-# Running into issues? [Open an issue](<https://github.com/KTools2202/birdbonk-game-jam-godot/issues/new>).\"}" \
             ${{ secrets.DISCORD_WEBHOOK_URL }}
